### ISSUE TITLE
Re-design KIWI PCB revision 1.1

### ISSUE THREAD

**Issue by Frankvd81** [SWAT-engineering/kiwi-air-monitor#33]
- [x] Instantiation of rev1.1 design database
- [x] bug fix: Rotate the OLED display connector 180degree
- [x] Modify the connector for the new MH-Z19-C with cable connector
- [x] Review placement of the BME280. The reported temperature is too high
- [x] Connector for the LED should move to a different location. Probably better use a 90degree connector for easier plug-in with short wires.
- [x] Check if we can move the pin controlling the LED to another Arduino pin. Currently it is assigned to D4, which is the same as the blue LED on the ESP8266 board. because of this we can not switch off the ESP8266 LED. Switch to either D3, D5 or D6 
- [x] make the pads bigger for all components, comparable to the esp8266 pads
- [x] put the kiwi bird logo on the pcb (get the svg from [font awesome](https://fontawesome.com/icons/kiwi-bird) by clciking the download button)
- [x] add small labels on the pcb to help with allignment of the components (just like for the led). so maybe just write the pin for the GND connection on all of them?
- [x] annotate/decorate the debug pins so that a user knows to ignore them
- [x] flip the rcwl board, so that the other side is faceing front

**Comment by Frankvd81** [comment]
I've started the redesign of the KIWI PCB. Add any issue found on the rev1.0 in this list so I can modify it for the next spin of the board

**Comment by DavyLandman** [comment]
I've added a few points to the list.

- Moving the LED pin: I'll take a look. I think D3 is a good candidate
- bme280 is a though one, it's a sensitive one.. maybe space it so that it's less close to the co2 sensor?
